export const pad = [
  {
    value: '0',
    start: 0,
    count: 1,
    diff: 0,
    hover: false,
    active: false,
    color: 'green',
  },
  {
    value: '3',
    start: 3,
    count: 1,
    diff: 0,
    hover: false,
    active: false,
    color: '#78172d',
  },
  {
    value: '6',
    start: 6,
    count: 1,
    diff: 0,
    hover: false,
    active: false,
    color: '#222328',
  },
  {
    value: '9',
    start: 9,
    count: 1,
    diff: 0,
    hover: false,
    active: false,
    color: '#78172d',
  },
  {
    value: '12',
    start: 12,
    count: 1,
    diff: 0,
    hover: false,
    active: false,
    color: '#78172d',
  },
  {
    value: '15',
    start: 15,
    count: 1,
    diff: 0,
    hover: false,
    active: false,
    color: '#222328',
  },
  {
    value: '18',
    start: 18,
    count: 1,
    diff: 0,
    hover: false,
    active: false,
    color: '#78172d',
  },
  {
    value: '21',
    start: 21,
    count: 1,
    diff: 0,
    hover: false,
    active: false,
    color: '#78172d',
  },
  {
    value: '24',
    start: 24,
    count: 1,
    diff: 0,
    hover: false,
    active: false,
    color: '#222328',
  },
  {
    value: '27',
    start: 27,
    count: 1,
    diff: 0,
    hover: false,
    active: false,
    color: '#78172d',
  },
  {
    value: '30',
    start: 30,
    count: 1,
    diff: 0,
    hover: false,
    active: false,
    color: '#78172d',
  },
  {
    value: '33',
    start: 33,
    count: 1,
    diff: 0,
    hover: false,
    active: false,
    color: '#222328',
  },
  {
    value: '36',
    start: 36,
    count: 1,
    diff: 0,
    hover: false,
    active: false,
    color: '#78172d',
  },
  {
    value: '2',
    start: 2,
    count: 1,
    diff: 0,
    hover: false,
    active: false,
    color: '#222328',
  },
  {
    value: '5',
    start: 5,
    count: 1,
    diff: 0,
    hover: false,
    active: false,
    color: '#78172d',
  },
  {
    value: '8',
    start: 8,
    count: 1,
    diff: 0,
    hover: false,
    active: false,
    color: '#222328',
  },
  {
    value: '11',
    start: 11,
    count: 1,
    diff: 0,
    hover: false,
    active: false,
    color: '#222328',
  },
  {
    value: '14',
    start: 14,
    count: 1,
    diff: 0,
    hover: false,
    active: false,
    color: '#78172d',
  },
  {
    value: '17',
    start: 17,
    count: 1,
    diff: 0,
    hover: false,
    active: false,
    color: '#222328',
  },
  {
    value: '20',
    start: 20,
    count: 1,
    diff: 0,
    hover: false,
    active: false,
    color: '#222328',
  },
  {
    value: '23',
    start: 23,
    count: 1,
    diff: 0,
    hover: false,
    active: false,
    color: '#78172d',
  },
  {
    value: '26',
    start: 26,
    count: 1,
    diff: 0,
    hover: false,
    active: false,
    color: '#222328',
  },
  {
    value: '29',
    start: 29,
    count: 1,
    diff: 0,
    hover: false,
    active: false,
    color: '#222328',
  },
  {
    value: '32',
    start: 32,
    count: 1,
    diff: 0,
    hover: false,
    active: false,
    color: '#78172d',
  },
  {
    value: '35',
    start: 35,
    count: 1,
    diff: 0,
    hover: false,
    active: false,
    color: '#222328',
  },
  {
    value: '1',
    start: 1,
    count: 1,
    diff: 0,
    hover: false,
    active: false,
    color: '#78172d',
  },
  {
    value: '4',
    start: 4,
    count: 1,
    diff: 0,
    hover: false,
    active: false,
    color: '#222328',
  },
  {
    value: '7',
    start: 7,
    count: 1,
    diff: 0,
    hover: false,
    active: false,
    color: '#78172d',
  },
  {
    value: '10',
    start: 10,
    count: 1,
    diff: 0,
    hover: false,
    active: false,
    color: '#222328',
  },
  {
    value: '13',
    start: 13,
    count: 1,
    diff: 0,
    hover: false,
    active: false,
    color: '#222328',
  },
  {
    value: '16',
    start: 16,
    count: 1,
    diff: 0,
    hover: false,
    active: false,
    color: '#78172d',
  },
  {
    value: '19',
    start: 19,
    count: 1,
    diff: 0,
    hover: false,
    active: false,
    color: '#78172d',
  },
  {
    value: '22',
    start: 22,
    count: 1,
    diff: 0,
    hover: false,
    active: false,
    color: '#222328',
  },
  {
    value: '25',
    start: 25,
    count: 1,
    diff: 0,
    hover: false,
    active: false,
    color: '#78172d',
  },
  {
    value: '28',
    start: 28,
    count: 1,
    diff: 0,
    hover: false,
    active: false,
    color: '#222328',
  },
  {
    value: '31',
    start: 31,
    count: 1,
    diff: 0,
    hover: false,
    active: false,
    color: '#222328',
  },
  {
    value: '34',
    start: 34,
    count: 1,
    diff: 0,
    hover: false,
    active: false,
    color: '#78172d',
  },
  {
    value: '2:1',
    start: 3,
    count: 12,
    diff: 3,
    hover: false,
    active: false,
    color: '#141517',
  },
  {
    value: '2:1',
    start: 2,
    count: 12,
    diff: 3,
    hover: false,
    active: false,
    color: '#141517',
  },
  {
    value: '2:1',
    start: 1,
    count: 12,
    diff: 3,
    hover: false,
    active: false,
    color: '#141517',
  },
  {
    value: '1st 12',
    start: 1,
    count: 12,
    diff: 1,
    hover: false,
    active: false,
    color: '#141517',
  },
  {
    value: '2nd 12',
    start: 13,
    count: 12,
    diff: 1,
    hover: false,
    active: false,
    color: '#141517',
  },
  {
    value: '3rd 12',
    start: 25,
    count: 12,
    diff: 1,
    hover: false,
    active: false,
    color: '#141517',
  },
  {
    value: '1 to 18',
    start: 1,
    count: 18,
    diff: 1,
    hover: false,
    active: false,
    color: '#141517',
  },
  {
    value: 'EVEN',
    start: 2,
    count: 18,
    diff: 2,
    hover: false,
    active: false,
    color: '#141517',
  },
  {
    value: 'RED',
    start: -1,
    count: 0,
    diff: 0,
    hover: false,
    active: false,
    color: '#78172d',
  },
  {
    value: 'BLACK',
    start: -2,
    count: 0,
    diff: 0,
    hover: false,
    active: false,
    color: '#222328',
  },
  {
    value: 'ODD',
    start: 1,
    count: 18,
    diff: 2,
    hover: false,
    active: false,
    color: '#141517',
  },
  {
    value: '19 to 36',
    start: 19,
    count: 18,
    diff: 1,
    hover: false,
    active: false,
    color: '#141517',
  },
]
